### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ZenaMel** [Sagar-Goyal/Quizler#1]
Hey @Sagar-Goyal,

Would you mind adding a licence (MIT or else)? Would be awesome!

**Comment by Sagar-Goyal** [comment]
@Zenahr It would be great but I am a newbie and didn't know how to get one...can you help me out?

**Comment by ZenaMel** [comment]
Sure @Sagar-Goyal.
Create a file named ´LICENSE´ (without an extension) inside your repository.
Add a suitable license text to it. Most open-source projects use the MIT-license. You can find that here: https://opensource.org/licenses/MIT

Hope it helps.

PS: Take a look at https://github.com/facebook/react/blob/main/LICENSE to see how they did it.

**Comment by Sagar-Goyal** [comment]
Done. Thanks for the help.
